version: '3.1'

services:
  app:
    build:
      context: /.
    container_name: shuttersky
    ports:
      - "8080:8080"
    environment:
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5444
        - DB_NAME=shuttersky

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shuttersky